apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sparsom-api
  namespace: tbd
  labels:
    team: tbd
spec:
  port: 8080
  liveness:
    path: isalive
    initialDelay: 1
  readiness:
    path: isready
    periodSeconds: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 64Mi
  prometheus:
    enabled: true
    path: /metrics
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: spanner
        - application: speil
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  openSearch:
    access: read
    instance: sparsom
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
