apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sparsom
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  envFrom:
    - secret: google-sql-helse-spleis-spleis-sparsom-9544ddd9
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        databases:
          - name: sparsom
            envVarPrefix: DATABASE
            users:
            - name: sparsom-api
            - name: sparsom-opprydding
            - name: spesialist-migrering
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-sparsom-v1
    - name: KAFKA_RESET_POLICY
      value: earliest
    - name: DATABASE_SPARSOM_REGION
      value: "europe-north1"
    - name: DATABASE_SPARSOM_INSTANCE
      value: "helse-spleis"