apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: tbd
    db: sparsom
  name: sparsom-job
  namespace: tbd
spec:
  image: {{image}}
  parallelism: 60
  resources:
    limits:
      cpu: 500m
      memory: 4096Mi
  secureLogs:
    enabled: true
  envFrom:
    - secret: google-sql-sparsom
    - secret: google-sql-spleis-spleis-sparsom-e28cfed2
  openSearch:
    access: readwrite
    instance: sparsom
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: tbd-prod-eacd
        role: roles/cloudsql.client
  env:
    - name: DATABASE_REGION
      value: "europe-north1"
    - name: DATABASE_INSTANCE
      value: sparsom
    - name: DATABASE_SPARSOM_REGION
      value: "europe-north1"
    - name: DATABASE_SPARSOM_INSTANCE
      value: "helse-spleis"
