apiVersion: aiven.io/v1alpha1
kind: ServiceIntegration
metadata:
  labels:
    team: tbd
  name: opensearch-tbd-sparsom
  namespace: tbd
spec:
  project: nav-prod
  integrationType: prometheus
  destinationEndpointId: 76685598-1048-4f56-b34a-9769ef747a92
  sourceServiceName: opensearch-tbd-sparsom